config/routes.rb
Rails.application.routes.draw do

  resources :pools, except: [:update, :edit, :new], shallow: true do
    resources :loans, except: [:index] do
      resources :payouts, except: [:index, :show]
    end
  end

  root 'pools#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  amount                   :decimal(, )      not null
#  created_at               :datetime         not null
#  debt_paid                :decimal(, )      default(0.0)
#  delinquency_rate         :decimal(, )
#  id                       :integer          not null, primary key
#  interest_paid            :decimal(, )      default(0.0)
#  legal_entity             :string
#  monthly_debt_payment     :decimal(, )
#  monthly_interest_payment :decimal(, )
#  period                   :integer
#  pool_id                  :integer
#  rate                     :decimal(, )      not null
#  term                     :integer          not null
#  total_monthly_payment    :decimal(, )
#  total_payment            :decimal(, )
#  updated_at               :datetime         not null
#  yield                    :decimal(, )      default(0.0)
#

class Loan < ApplicationRecord

  belongs_to :pool
  has_many :payouts, dependent: :destroy

  validates :rate, :term, :amount, presence: true

  before_save :populate_values

  private

  def populate_values
    expected_interest_amount = amount*(rate/100.0)*(term/12.0)

    self.total_payment = amount+expected_interest_amount

    if term == 0
      self.monthly_interest_payment = 0
      self.monthly_debt_payment = 0
    else
      self.monthly_interest_payment = expected_interest_amount/term
      self.monthly_debt_payment = amount/term
    end

    self.total_monthly_payment = monthly_debt_payment+monthly_interest_payment
  end
end

app/models/payout.rb
# == Schema Information
#
# Table name: payouts
#
#  amount     :decimal(, )      not null
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  loan_id    :integer
#  month      :integer          not null
#  updated_at :datetime         not null
#

class Payout < ApplicationRecord

  belongs_to :loan

  validates :amount, :month, presence: true
end

app/models/pool.rb
# == Schema Information
#
# Table name: pools
#
#  actual_yield   :decimal(, )      default(0.0)
#  created_at     :datetime         not null
#  expected_yield :decimal(, )      default(0.0)
#  id             :integer          not null, primary key
#  updated_at     :datetime         not null
#

class Pool < ApplicationRecord
  has_many :loans, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_pool, only: [:new, :create]
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @loan = @pool.loans.new
  end

  def edit
  end

  def create
    @loan = @pool.loans.new(loan_params)

    if @loan.save
      Recalculation.update_pool_values(@loan.pool)

      redirect_to pool_url(@pool), notice: 'Loan was successfully created.'
    else
      render :new
    end
  end

  def update
    if @loan.update(loan_params)
      Recalculation.update_pool_values(@loan.pool)

      redirect_to pool_url(@loan.pool), notice: 'Loan was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pool = @loan.pool
    @loan.destroy

    redirect_to pool_url(@pool), notice: 'Loan was successfully destroyed.'
  end

  private

  def set_pool
    @pool = Pool.find(params[:pool_id])
  end

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:amount,
                                 :delinquency_rate,
                                 :legal_entity,
                                 :period,
                                 :pool_id,
                                 :rate,
                                 :term)
  end
end

app/controllers/payouts_controller.rb
class PayoutsController < ApplicationController
  before_action :set_loan, only: [:new, :create]
  before_action :set_payout, only: [:edit, :update, :destroy]

  def new
    @payout = @loan.payouts.new
  end

  def edit
  end

  def create
    @payout = @loan.payouts.new(payout_params)

    if @payout.save
      Recalculation.update_loan_values(@payout.loan)

      redirect_to loan_url(@loan), notice: 'Payout was successfully created.'
    else
      render :new
    end
  end

  def update
    if @payout.update(payout_params)
      Recalculation.update_loan_values(@payout.loan)

      redirect_to loan_url(@payout.loan), notice: 'Payout was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @loan = @payout.loan
    @payout.destroy

    redirect_to loan_url(@loan), notice: 'Payout was successfully destroyed.'
  end

  private

  def set_loan
    @loan = Loan.find(params[:loan_id])
  end

  def set_payout
    @payout = Payout.find(params[:id])
  end

  def payout_params
    params.require(:payout).permit(:month, :amount, :loan_id)
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :destroy]

  def index
    @pools = Pool.all.order(created_at: :desc)
  end

  def show
  end

  def create
    if params[:file].present?
      XlsxParser.new.parse_file(params[:file])
      render json: { status: 201 }
    else
      @pool = Pool.create
      redirect_to pools_url, notice: 'Pool was successfully created.'
    end
  end

  def destroy
    @pool.destroy
    redirect_to pools_url, notice: 'Pool was successfully destroyed.'
  end

  private

  def set_pool
    @pool = Pool.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_topnavbar.html.slim
.row.border-bottom.white-bg
  nav.navbar.navbar-static-top role="navigation"
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        = icon 'reorder'
      = link_to 'Yield Calc', root_path, class: 'navbar-brand'

    .navbar-collapse.collapse#navbar
      ul.nav.navbar-nav
        li
          = link_to 'Список пулов', pools_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title Yieldcalc
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'

  body.md-skin.top-navigation
    #wrapper
      #page-wrapper.gray-bg
        = render 'layouts/topnavbar'
        .wrapper.wrapper-content
          .container
            = yield
    = javascript_include_tag 'application'

app/views/loans/_form.html.slim
= simple_form_for([@pool, @loan]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :legal_entity
    = f.input :rate
    = f.input :term
    = f.input :amount
    = f.input :delinquency_rate
    = f.input :period
    = f.input :monthly_debt_payment, readonly: true
    = f.input :monthly_interest_payment, readonly: true
    = f.input :total_monthly_payment, readonly: true
    = f.input :total_payment, readonly: true

  .form-actions
    = f.button :submit, class: 'btn btn-primary btn-outline'

app/views/loans/edit.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Вернуться к кредиту',
                      loan_path(@loan),
                      class: 'btn btn-success btn-outline pull-right'
              = link_to 'Вернуться к пулу',
                      pool_path(@loan.pool),
                      class: 'btn btn-success btn-outline pull-right'
              h2
                | Редактирование кредита №
                =< @loan.id
        .row
          .col-md-12
            = render 'form'

app/views/loans/new.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Вернуться к пулу',
                      pool_path(@loan.pool),
                      class: 'btn btn-success btn-outline pull-right'
              h2 Добавление кредита
        .row
          .col-md-12
            = render 'form'

app/views/loans/show.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Редактировать', edit_loan_path(@loan), class: 'btn btn-success btn-outline pull-right'
              = link_to 'Вернуться к пулу', pool_path(@loan.pool), class: 'btn btn-success btn-outline pull-right'
              h2
                | Кредит юрлица
                =< @loan.legal_entity
        .row
          .col-md-6
            dl.dl-horizontal
              dt Сумма:
              dd = @loan.amount
              dt Срок(мес):
              dd = @loan.term
              dt Ставка(годовых):
              dd = "#{@loan.rate}%"
              dt Ставка при просрочке:
              dd = "#{@loan.delinquency_rate|| '-'}%"
              dt Период:
              dd = @loan.period

          .col-md-6
            dl.dl-horizontal
              dt Ежемесячный по долгу:
              dd = number_with_precision(@loan.monthly_debt_payment, precision: 2)
              dt Ежемесячный по процентам:
              dd = number_with_precision(@loan.monthly_interest_payment, precision: 2)
              dt Общий ежемесячный:
              dd = number_with_precision(@loan.total_monthly_payment, precision: 2)
              dt Сумма выплаты:
              dd = number_with_precision(@loan.total_payment, precision: 2)
        .row
          .col-md-4
            h3
              | Выплачено процентов:
              =< number_with_precision(@loan.interest_paid, precision: 2)
          .col-md-4
            h3
              | Выплачено ОД:
              =< number_with_precision(@loan.debt_paid, precision: 2)
          .col-md-4
            h3
              | Доходность(годовых):
              =< number_with_precision(@loan.yield, precision: 2)



.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Добавить выплаты',
                      new_loan_payout_path(@loan),
                      class: 'btn btn-success btn-outline pull-right'
              h2 Выплаты по кредиту

        .row
          .col-md-12
            table.table.table-striped.table-responsive
              thead
                tr
                  th Месяц
                  th Сумма
                  th col=2

              tbody
                - @loan.payouts.order(created_at: :desc).each do |payout|
                  tr
                    td = payout.month
                    td = number_with_precision(payout.amount, precision: 2)
                    td
                      = link_to edit_payout_path(payout) do
                        = icon 'fa fa-edit fa-lg'
                    td
                      = link_to payout, data: { confirm: 'Вы уверены?' }, method: :delete do
                        = icon 'fa fa-trash-o text-danger fa-lg'

app/views/payouts/_form.html.slim
= simple_form_for([@loan,@payout]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :month
    = f.input :amount

  .form-actions
    = f.button :submit, class: 'btn btn-primary btn-outline'

app/views/payouts/edit.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Вернуться к кредиту',
                      loan_path(@payout.loan),
                      class: 'btn btn-success btn-outline pull-right'
              h2
                | Редактирование выплаты №
                =< @payout.id
        .row
          .col-md-12
            = render 'form'

app/views/payouts/new.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Вернуться к кредиту',
                      loan_path(@payout.loan),
                      class: 'btn btn-success btn-outline pull-right'
              h2 Добавление выплаты
        .row
          .col-md-12
            = render 'form'

app/views/pools/index.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .text-center
          = form_tag pools_path, multipart: true, class: 'dropzone' do
            .fallback
              = file_field_tag :file
              = submit_tag 'Загрузить файл'
            .dz-message
              = icon 'fa fa-cloud-upload fa-3x'
              p Перетащите файл сюда или нажмите на облачко


.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Добавить новый пул',
                      pools_path,
                      method: :post,
                      class: 'btn btn-success btn-outline pull-right'
              h2 Список пулов
        .row
          .col-md-12
            table.table.table-striped.table-responsive
              thead
                tr
                  th Идентификатор
                  th Дата создания
                  th Ожидаемая доходность(%)
                  th Фактическая доходность(%)
                  th col=2

              tbody
                - @pools.each do |pool|
                  tr
                    td = pool.id
                    td = pool.created_at.to_formatted_s(:short)
                    td = number_with_precision(pool.expected_yield, precision: 2)
                    td = number_with_precision(pool.actual_yield, precision: 2)
                    td
                      = link_to pool do
                        = icon 'fa fa-eye fa-lg'
                    td
                      = link_to pool, data: { confirm: 'Вы уверены?' }, method: :delete do
                        = icon 'fa fa-trash-o fa-lg text-danger'

app/views/pools/show.html.slim
.row
  .col-md-12
    .ibox
      .ibox-content
        .row
          .col-md-12
            .m-b-md
              = link_to 'Вернуться к пулам',
                      pools_path,
                      class: 'btn btn-success btn-outline pull-right'
              = link_to 'Добавить новый кредит',
                      new_pool_loan_path(@pool),
                      class: 'btn btn-primary btn-outline pull-right'
              h2
                | Список кредитов(юрлиц) в пуле №
                =< @pool.id
        .row
          .col-md-12
            table.table.table-striped.table-responsive
              thead
                tr
                  th Юрлицо
                  th Ставка годовых(%)
                  th Доходность годовых(%)
                  th col=3

              tbody
                - @pool.loans.order(created_at: :desc).each do |loan|
                  tr
                    td = loan.legal_entity
                    td = number_with_precision(loan.rate, precision: 2)
                    td = number_with_precision(loan.yield, precision: 2)
                    td
                      = link_to loan_path(loan) do
                        = icon 'fa fa-eye fa-lg'
                    td
                      = link_to edit_loan_path(loan) do
                        = icon 'fa fa-edit fa-lg'
                    td
                      = link_to loan, data: { confirm: 'Вы уверены?' }, method: :delete do
                        = icon 'fa fa-trash-o text-danger fa-lg'